export const fallbackCategories = [
  {
    id: 'fallback-category-1',
    name: 'Botanische Motive',
    slug: 'botanische-motive',
    description: 'Frische, elegante Designs für Kuchen und Dessertteller.',
    is_active: true,
    sort_order: 1,
  },
  {
    id: 'fallback-category-2',
    name: 'Feierliche Kollektionen',
    slug: 'feierliche-kollektionen',
    description: 'Glanzvolle Prints für Geburtstage, Hochzeiten und Sonderanlässe.',
    is_active: true,
    sort_order: 2,
  },
];

export const fallbackProducts = [
  {
    id: 'fallback-product-1',
    name: 'Blütenzauber',
    slug: 'blutenzauber',
    price: 12.9,
    short_description: 'Helles, elegantes Papier mit feinen blühenden Motiven.',
    description: 'Perfekt für elegante Kuchen und kreative Dessertdekorationen.',
    featured_image_url: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=900&q=80',
    category_id: 'fallback-category-1',
    categories: { name: 'Botanische Motive', slug: 'botanische-motive' },
    is_active: true,
    is_featured: true,
    size: '20 x 20 cm',
    paper_type: 'Essbares Zuckerpapier',
  },
  {
    id: 'fallback-product-2',
    name: 'Goldene Abendstern',
    slug: 'goldene-abendstern',
    price: 15.5,
    short_description: 'Ein glamouröses Design für besondere Feierlichkeiten.',
    description: 'Ideal für Hochzeiten, Geburtstage und aufwändige Torten.',
    featured_image_url: 'https://images.unsplash.com/photo-1551024601-bec78aea704b?auto=format&fit=crop&w=900&q=80',
    category_id: 'fallback-category-2',
    categories: { name: 'Feierliche Kollektionen', slug: 'feierliche-kollektionen' },
    is_active: true,
    is_featured: true,
    size: '25 x 25 cm',
    paper_type: 'Essbares Zuckerpapier',
  },
];
